title: 对酒当歌分享
description: 资源都是免费分享，有电影，美剧，日剧，国产剧，游戏，短剧，音乐，课程等。
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# 将路径url设置为将显示的徽标而不是标题
logo: "/assets/images/apple-touch-icon-152x152.png"

# 为浏览器网站图标将显示的图标设置路径url
favicon_ico: "/assets/images/favicon.ico"

# 启用或禁用站点搜索
# 支持true default和false
search_enabled: true
search:
  # 将页面分成可以单独搜索的部分
  # 支持1-6 默认2
  heading_level: 2
  # 每个搜索结果的最大预览量
  # Default: 3
  previews: 3
  # 在预览中匹配的单词之前显示的最大字数
  # Default: 5
  preview_words_before: 5
  # 在预览中匹配的单词后显示的最大字数
  # Default: 10
  preview_words_after: 10
  # 设置搜索令牌分隔符
  # Default: /[\s\-/]+/
  # 启用对连字符搜索的支持
  tokenizer_separator: /[\s/]+/
  # 在搜索结果中显示相关url
  # 支持true default和false
  rel_url: true
  # 启用或禁用出现在每个页面右下角的搜索按钮
  # 支持 true 或 false (default)
  button: false
  # 在mac操作系统上按ctrl焦点快捷键或cmd焦点快捷键可将搜索输入集中
  focus_shortcut_key: 'k'

  # 用于右上方导航的辅助链接
aux_links:
  "一键加Q群":
    - "https://qm.qq.com/q/4bJ9hEzh3y"

# 使Aux链接在新选项卡中打开默认为false
aux_links_new_tab: false

# 标题锚链接出现在悬停在页面内容中的h1-h6标签上
# 允许用户深度链接到页面上的特定标题。
#
# 支持true（默认）或false
heading_anchors: true

# 页脚内容
# 出现在每个页面的主要内容的底部
# 注意：footer_content选项已弃用，并将在未来的主要版本中删除。请使用`_includes/footer_custom.html`获取更多robus
markup / liquid-based content.
footer_content: "1111111111111111111 <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# 页脚上次编辑的时间戳
last_edit_timestamp: true # 显示或隐藏编辑时间页必须在页眉中定义上次修改日期
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# 在Git Hub上编辑这个页面的链接文本
gh_edit_link: true # 显示或隐藏编辑此页链接
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
gh_edit_branch: "main" # 为您的文档提供服务的分支
# 编辑你的文件来源的源文档
gh_edit_view_mode: "tree" # 如果您希望用户立即跳转到编辑器，请使用“tree”或“edit”。

# 配色方案支持“亮”"light"（默认）和“暗”"dark"
color_scheme: dark

# 启用或禁用站点搜索
# 支持true default和false
search_enabled: true

# 将页面拆分为可以单独搜索的部分
# 支持1 - 6，默认为2
search.heading_level: 2

# 在预览中匹配的单词之前显示的最大单词量
# 默认值：5
search.previews: 3

# 在预览中匹配的单词之前显示的最大单词量
# 默认值：5
search.preview_words_before: 5

# 在预览中匹配的单词后显示的最大单词量
# 默认值：10
search.preview_words_after: 10

# 在搜索结果中显示相关url
# 支持true default和false
search.rel_url: false

# 启用或禁用出现在每个页面右下角的搜索按钮
# 支持true或false（默认）
search.button: true