title: 对酒当歌分享
description: 资源都是免费分享，有电影，美剧，日剧，国产剧，游戏，短剧，音乐，课程等。
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# 将路径url设置为将显示的徽标而不是标题
logo: "/assets/images/apple-touch-icon-152x152.png"

# 为浏览器网站图标将显示的图标设置路径url
favicon_ico: "/assets/images/favicon.ico"

